#!/bin/bash

echo 9 >/sys/class/gpio/export
echo 11 >/sys/class/gpio/export

echo out >/sys/class/gpio/gpio9/direction
echo out >/sys/class/gpio/gpio11/direction

echo 1 >/sys/class/gpio/gpio9/value
echo 1 >/sys/class/gpio/gpio11/value
