#!/bin/bash

#modprobe i2c-dev
#sleep 1

echo "Putting headphone outs always on"
i2cset -f -y 2 0x4a 0x04 0xaf
sleep 0.25

echo "Putting headphone volume to 0dB"
i2cset -f -y 2 0x4a 0x22 0x00
sleep 0.25

echo "Starting playback of sine @440Hz on LR channels in alternate mode"
#sr=8000
#sr=16000
#sr=32000
#sr=44100 # is not supported by codec with 12MHz mclk see datasheet
sr=48000
#sr=96000
echo "Sampling rate: $sr"
frmt=S16_LE
#frmt=S24_LE
#frmt=S32_LE # format not supported by codec driver
echo "Format: $frmt"
speaker-test -t sine -f 440 -F $frmt -c 2 -r $sr -D hw:0,0
