#!/bin/bash

#modprobe i2c-dev
#sleep 1

echo "Enabling AIN3A AIN3B"
i2cset -f -y 2 0x4a 0x08 0x40
sleep 0.25
i2cset -f -y 2 0x4a 0x09 0x40
sleep 0.25

echo "Starting recording 30s of LR channels"
#sr=8000
#sr=16000
#sr=32000
#sr=44100 # is not supported by codec with 12MHz mclk see datasheet
sr=48000
#sr=96000
echo "Sampling rate: $sr"
frmt=S16_LE
#frmt=S24_LE # format not implemented in speaker-test utility
#frmt=S32_LE # format not supported by codec driver
echo "Format: $frmt"
arecord --dump-hw-params -D hw:0,0 -t wav --max-file-time 30 -c 2 -r $sr -f $frmt --vumeter=stereo AIN3A_AIN3B_stereo_$frmt_$sr.wav
